layout: sidebar
style: dark

plugins:
  - jekyll-octicons
  - jekyll-github-metadata
  - jemoji

permalink: /:year/:month/:day/:title/

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "post"

projects:
  sort_by: pushed
  # sort_by options:
  #   - 
  #   - stars
  limit: 9
  exclude:
    forks: true
    projects:
    # - repo-name
repositories:
  - TheoremJS
  - Euler
  - DisplayJS
  - Descartes
  - ProType
  - EyeJS
  - Glottologist
  - Neuron
  - Timeline
  - StudIO
  - ctoUI
  - BroadcastJS
social_media:
  # behance: your_username
  # dribbble: your_username
  # facebook: your_username
  linkedin: "arthur-guiot-4a68a91bb"
  medium: "@arthur_guiot"
  stackoverflow: 6598037
  # telegram: your_username
  twitter: "arthur_guiot"
  # youtube: your_username
  # vk: your_username

topics:
  - name: Swift
    web_url: https://github.com/topics/swift
    image_url: https://raw.githubusercontent.com/github/explore/8fb8b0e9d61d266721825ce116060773ea2503c2/topics/swift/swift.png
    
  - name: Node JS
    web_url: https://github.com/topics/nodejs
    image_url: https://raw.githubusercontent.com/github/explore/fd96fceccf8c42c99cbe29cf0f8dcc4736fcb85a/topics/nodejs/nodejs.png

  - name: JavaScript
    web_url: https://github.com/topics/javascript
    image_url: https://raw.githubusercontent.com/github/explore/6c6508f34230f0ac0d49e847a326429eefbfc030/topics/javascript/javascript.png
    
  - name: Python
    web_url: https://github.com/topics/python
    image_url: https://raw.githubusercontent.com/github/explore/6c6508f34230f0ac0d49e847a326429eefbfc030/topics/python/python.png
    
  - name: Next.js
    web_url: https://github.com/topics/nextjs
    image_url: https://raw.githubusercontent.com/github/explore/28b02bbc9ad9f7a503c43775aebeb515dc2da5fc/topics/nextjs/nextjs.png
